### ISSUE TITLE
How to add sensors in HA?

### ISSUE THREAD

**Issue by andrejs2** [MindFreeze/hass-evnotify#2]
Thanks for the addon!

I have one question (I'm quite noob in HA)...how can I add sensors? I know how the sensor configuration should look like in configuration.yaml, but what types and names are available?
Do you have any example?

Thanks!!!

**Comment by MindFreeze** [comment]
Once you add the config to your sensors like in the README and restart, you should have a `sensor.evnotify_soc` sensor with the battery % and bunch of other info in the attributes

**Comment by caitotheonlypotato** [comment]
I have 2 EVs with EVNotify, so I was wondering will this addon support 2 instances (a 2nd platform: entry with separate aKey and passwd)?

**Comment by MindFreeze** [comment]
@caitotheonlypotato I haven't tried it but in theory it should work like that. I suspect HA will just set the second entity id to `sensor.evnotify_soc_2`
You can then change the names in `customize.yaml`
